<?php

//This architect plugin manages dashboards. This is an alternative to SchemaRoute which allows certain routes to have a default page with arbitrary content instead of the procedural page generated by the schema router.

function ArchitectDashboards(){
  //TODO Create session object containing routes to look for, or use it. then show anything at the current route
}
